# Generated by Django 5.2.11 on 2026-02-27 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('creditos', models.IntegerField()),
                ('descripcion', models.TextField(blank=True)),
                ('estudiantes', models.ManyToManyField(blank=True, related_name='asignaturas_inscritas', to=settings.AUTH_USER_MODEL)),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas_dictadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
