# Generated by Django 5.2.11 on 2026-04-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_usuario_limite_conflictos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('hecha', 'Hecha'), ('pospuesta', 'Pospuesta')], default='pendiente', max_length=10),
        ),
    ]
