# Generated by Django 5.1.4 on 2026-05-01 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_subtask_estado_pendiente'),
        ('api', '0012_alter_subtask_estado'),
    ]

    operations = [
    ]
