# Generated by Django 5.2.11 on 2026-05-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_20260501_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='forzada',
            field=models.BooleanField(default=False),
        ),
    ]
